version: "3.3"

networks:
  star_network:
volumes:
  data:
  mqdata:

services:
  nacos:
    image: nacos/nacos-server:2.0.2
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "MODE=standalone"#单机模式启动
    networks:
      - star_network
  mysql:
    image: mysql:5.7
    ports:
      - "3309:3306"
    networks:
      - star_network
    volumes:
      - data:/var/lib/mysql
      - ./star.sql:/docker-entrypoint-initdb.d/star.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=star"
  redis:
    image: redis:5.0.10
    ports:
      - "6379:6379"
    volumes:
      #      - redisdata:/data
      - ./datadir:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs:/logs

  rabbitmq:
    image: rabbitmq:3.7.28-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - star_network
#    env_file:
#      - ./rabbitmq.env
    volumes:
      - mqdata:/var/lib/rabbitmq

  es:
    image: elasticsearch:6.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./ik/:/usr/share/elasticsearch/plugins/ik
      - ./jvm.options:/usr/share/elasticsearch/config/jvm.options
    networks:
      - star_network

  kibana:
    image: kibana:6.8.0
    ports:
      - 5601:5601
    networks:
      - star_network
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - es



#  admins:
#    build:
#      context: ./images/admins
#      dockerfile: Dockerfile
#    ports:
#      - "8980:8980"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#
#  category:
#    build:
#      context: ./images/category
#      dockerfile: Dockerfile
#    ports:
#      - "8981:8981"
#    depends_on:
#      - nacos
#      - mysql
#      - redis
#  gateway:
#    build:
#      context: ./images/gateway
#      dockerfile: Dockerfile
#    ports:
#      - "9999:9999"
#    depends_on:
#      - nacos
#      - mysql
#      - redis
#  users:
#    build:
#      context: ./images/users
#      dockerfile: Dockerfile
#    ports:
#      - "8982:8982"
#    depends_on:
#      - nacos
#      - mysql
#      - redis
#  videos:
#    build:
#      context: ./images/videos
#      dockerfile: Dockerfile
#    ports:
#      - "8983:8983"
#    depends_on:
#      - nacos
#      - mysql
#      - redis
#
#  nginx:
#    image: nginx:1.21.1
#    ports:
#      - "80:80"
#    volumes:
#      - ./admin-dist:/usr/share/nginx/html:ro