version: "3.9"

networks:
  star_network:
volumes:
  data:
services:
  nacos:
    image: nacos/nacos-server:2.0.2
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "MODE=standalone"#单机模式启动
    networks:
      - star_network
  mysql:
    image: mysql:5.7
    ports:
      - "3309:3306"
    networks:
      - star_network
    volumes:
      - data:/var/lib/mysql
      - ./star.sql:/docker-entrypoint-initdb.d/star.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=star"