server:
  port: 9999
spring:
  application:
    name: API-GATEWAY
  cloud:
    nacos:
      server-addr: http://localhost:8848
    gateway:
      routes: #用来配置路由规则  id uri path
#        admin router
        - id: admins_router
          uri: lb://API-ADMINS
          predicates:
            - Path=/admin/tokens,/admin/admin-user,/admin/tokens/**
          filters:
            - StripPrefix=1

#         category router
        - id: category_router
          uri: lb://API-CATEGORYS
          predicates:
            - Path=/admin/categories/**
          filters:
            - StripPrefix=1
            - Token=true,star
#        videos router
        - id: videos_router
          uri: lb://API-VIDEOS
          predicates:
            - Path=/admin/videos/**
          filters:
            - StripPrefix=1
            - Token=true
#          users router
        - id: users_router
          uri: lb://API-USERS
          predicates:
            - Path=/admin/users/**
          filters:  #去掉一级目录
            - StripPrefix=1
            - Token=true
      globalcors:  #解决跨域
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  redis:
    host: localhost
    port: 6379
